
extract_frames:
  # Link to the csv file with video names,key developmental timepoints and co-ordinates for cropping (optional), see template
  AllNotes: Preprocessing/Annotations.csv
  # Folder of input videos
  inputfolder: Preprocessing/Input videos
  outputfolder: Preprocessing/Outputs/
  #The developmental stage you are interested in, make sure it matches a column heading in the Annotations csv file
  stage: PN
  #if you want cropped images, 'N' if you do not want images to be cropped
  cropping:  'Y' 
  # The list of required offsets
  offset: [0,-1,-2]
find_cropping_coords:
  # The folder with raw input videos
  cropping_input_folder: 'C:/1. Incoming data/testvids'
